name: cd

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.26.0"

      - name: Build application
        run: ./scripts/buildprod.sh

      - id: "auth"
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: "${{ secrets.GCP_CREDENTIALS }}"

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v3"
        with:
          version: ">= 363.0.0"

      - name: "Deploy to Artifact Registry"
        run: gcloud builds submit \
          --tag europe-north1-docker.pkg.dev/cognitotest-464816/notely-ar-repo/notely:latest \
          --service-account="projects/cognitotest-464816/serviceAccounts/cloud-run-deployer@cognitotest-464816.iam.gserviceaccount.com" \
          .
